// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqzSh6CnbAM2E9gfiIB8zacshh3otIEBM',
    appId: '1:256002788432:web:d2b8c0726f427b0d365555',
    messagingSenderId: '256002788432',
    projectId: 'kibzar-ea8f8',
    authDomain: 'kibzar-ea8f8.firebaseapp.com',
    storageBucket: 'kibzar-ea8f8.firebasestorage.app',
    measurementId: 'G-Y7KBE8G4EL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSQFK4g1tizl0yuuN9Z43xJNtN6QJ7xwE',
    appId: '1:256002788432:android:5df9e1576c724850365555',
    messagingSenderId: '256002788432',
    projectId: 'kibzar-ea8f8',
    storageBucket: 'kibzar-ea8f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfVHAGKLyIDpm3SHUeSuBByw0lhXvXTdM',
    appId: '1:256002788432:ios:7a7480af761d73e3365555',
    messagingSenderId: '256002788432',
    projectId: 'kibzar-ea8f8',
    storageBucket: 'kibzar-ea8f8.firebasestorage.app',
    iosBundleId: 'com.example.alPazar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfVHAGKLyIDpm3SHUeSuBByw0lhXvXTdM',
    appId: '1:256002788432:ios:7a7480af761d73e3365555',
    messagingSenderId: '256002788432',
    projectId: 'kibzar-ea8f8',
    storageBucket: 'kibzar-ea8f8.firebasestorage.app',
    iosBundleId: 'com.example.alPazar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqzSh6CnbAM2E9gfiIB8zacshh3otIEBM',
    appId: '1:256002788432:web:cb7b460d0cc8153b365555',
    messagingSenderId: '256002788432',
    projectId: 'kibzar-ea8f8',
    authDomain: 'kibzar-ea8f8.firebaseapp.com',
    storageBucket: 'kibzar-ea8f8.firebasestorage.app',
    measurementId: 'G-6ENYW7EY33',
  );
}
